/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.austral.ingsis;

public class OtherApp {
    public static void main(String[] args) {
        System.out.println("Hello People!");
    }
}
